config/routes.rb
Rails.application.routes.draw do

  resources :nomina_documents
  resources :dashboard
  resources :open_data
  resources :social_users
  resources :api_keys
  resources :verifications
  resources :ley_articulos, shallow: true do
    put 'validar_documento', on: :member
    resources :ley_fraccions do
      put 'validar_documento', on: :member
      collection do
        get 'new_import'
        post 'create_import'
        get 'download_import_file'
      end
    end
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :staffs do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :job_titles do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :ascriptions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :territorial_units do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :social_development_programs
  resources :suppliers
  resources :towns do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :states do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end

  resources :financial_document_types

  resources :projects, shallow: true do
    resources :project_activity_obras, shallow: true do
      resources :financial_documents do
        get 'new_with_type', on: :collection
      end
    end
    resources :project_activity_socials, shallow: true do
      resources :beneficiaries do
        collection do
          get 'new_import'
          post 'create_import'
          get 'download_import_file'
        end
      end
      resources :financial_documents do
        get 'new_with_type', on: :collection
      end
    end
    resources :project_activity_adquisicions, shallow: true do
      resources :financial_documents do
        get 'new_with_type', on: :collection
      end
    end
  end
  resources :key_analyticals do
    put :approve_changes, on: :member
    put :reject_changes, on: :member
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ppr_spending_destinations do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_uni_measure_units do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_are_areas
  resources :cat_ppr_digit_identifiers
  resources :cat_ppr_par_partida_especificas do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ppr_par_partida_genericas do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ppr_par_concepts do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ppr_par_chapters
  resources :cat_ppr_expense_types
  resources :cat_aci_institutional_activities do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ere_subresults do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ere_results do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ere_expending_focus do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_cfu_subfunctions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_cfu_functions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_cfu_finalities
  resources :cat_fon_funds
  resources :cat_fon_origin_resources
  resources :cat_fon_year_documents
  resources :cat_fon_specific_sources
  resources :cat_fon_generic_sources
  resources :cat_fon_funding_sources
  resources :cat_pgd_line_of_actions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_pgd_goals do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_pgd_objectives do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_pgd_area_of_opportunities do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_pgd_axis do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_gen_line_of_actions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_gen_strategies do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_gen_axis do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_der_line_of_actions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_der_strategies do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_der_human_rights do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end

  resources :comments
  resources :conversations, only: [:index, :show, :destroy] do
    post :mark_as_read, on: :member
    get :mark_all_as_read, on: :collection
  end
  resources :delayed_jobs
  resources :thing_categories
  resources :wizard
  resources :public_activity
  resources :thing_contacts
  resources :thing_parts
  resources :things do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end

  namespace :dynamic_select do
    get ':thing_id/thing_contacts', to: 'thing_contacts#index', as: 'thing_contacts' # el as: es para que el helper method sea 'dynamic_select_thing_contacts_path' y no 'dynamic_select_path'
  end

  namespace :dev do
    resources :catalog_cleaners do
      post :run_cleaner, on: :collection
    end
    resources :chucky_bots
    resources :examples do
      collection do
        get 'chartkick'
        get 'cors'
      end

    end
  end

  namespace :admin do
    root to: 'application#index'
    resources :settings
  end

  devise_for :users
  resources :users do
    get 'resend_password_instructions/:id', action: 'resend_password_instructions', on: :collection
    get 'mentionables', on: :collection
  end

  devise_for :api_users, controllers: { registrations: 'api_users/registrations', confirmations: 'api_users/confirmations', passwords: 'api_users/passwords' }
  resources :api_users do
    get 'error_when_confirmation', to: 'api_users/welcome#error_when_confirmation', on: :collection
    get 'check_credentials', to: 'api_users/welcome#check_credentials', on: :collection
  end
  get 'api_user_root', to: 'api_users/welcome#welcome'

  get 'set_viewing_year/:viewing_year', to: 'application#set_viewing_year'
  get "application/access_denied"

  get 'welcome/prueba'

  root to: 'dashboard#index'

  api_version(:module => "V1", :path => {:value => "v1"}, :defaults => {:format => "json"}) do
    resources :things
    resources :project_activity_obras
    resources :verifications
    resources :portal do
      collection do
        get :total_budget
        get :budget_by_chapter
        get :treemap
        get :suppliers
        get :mapa_obras
        get :financial_documents
        get :open_data
      end
    end
  end

  api_version(:module => "V2", :path => {:value => "v2"}, :defaults => {:format => "json"}) do
    resources :things
    resources :project_activity_obras
    resources :verifications
    resources :portal do
      collection do
        get 'total_budget/:year', action: 'total_budget'
        get :budget_by_chapter
        get 'treemap/:year', action: 'treemap'
        get 'suppliers/:year', action: 'suppliers'
        get 'mapa_obras/:year', action: 'mapa_obras'
        get 'financial_documents/:year', action: 'financial_documents'
        get :open_data
      end
    end
  end

end

app/controllers/chucky_bots_controller.rb
class ChuckyBotsController < ApplicationController
  load_and_authorize_resource except: :index, param_method: :chucky_bot_params

  # GET /chucky_bots
  def index
    @chucky_bots = do_index(ChuckyBot, params)
  end

  # GET /chucky_bots/1
  def show
  end

  # GET /chucky_bots/new
  def new
    #convierto los role names en keys con values nil en una hash
    @chucky_bot.authorization = Hash[Role.all.pluck(:name).map {|key| [key, nil]}]
    @chucky_bot.public_activity = {actions: nil, notes: nil}
  end

  # GET /chucky_bots/1/edit
  def edit
  end

  # POST /chucky_bots
  def create
    if @chucky_bot.save
      redirect_to @chucky_bot, notice: t("simple_form.flash.successfully_created")
    else
      generate_flash_msg(@chucky_bot)
      render :new
    end
  end

  # PATCH/PUT /chucky_bots/1
  def update
    if @chucky_bot.update(chucky_bot_params)
      redirect_to @chucky_bot, notice: t("simple_form.flash.successfully_updated")
    else
      generate_flash_msg(@chucky_bot)
      render :edit
    end
  end

  # DELETE /chucky_bots/1
  def destroy
    @chucky_bot.destroy
    redirect_to chucky_bots_url, notice: t("simple_form.flash.successfully_destroyed")
  end

  private

    # Only allow a trusted parameter "white list" through.
    def chucky_bot_params
      params.require(:chucky_bot).permit(:underscore_model_name, :i18n_singular_name, :i18n_plural_name, :migrate,
                                         {authorization: Role.all.pluck(:name).concat([:notes])},
                                         {public_activity: [:actions, :notes]},
                                         {fields_attributes: [:name, :field_type, :i18n_name, :_destroy, :id,
                                                              formats_options: [:index, :show, :all],
                                                              validations_options: [:notes, validates: []],
                                                              association_options: [:no_relationize, :drop_down_type, :dependent_on_parent] ]}
      )
    end
end

app/controllers/dev/chucky_bots_controller.rb
class Dev::ChuckyBotsController < ApplicationController
  # la opcion class: 'ChuckyBot' es para que no intente con Dev::ChuckyBot
  load_resource except: [:index, :new], param_method: :chucky_bot_params, class: 'ChuckyBot'
  authorize_resource except: :index, param_method: :chucky_bot_params, class: 'ChuckyBot'

  # GET /chucky_bots
  def index
    @chucky_bots = indexize(ChuckyBot)
  end

  # GET /chucky_bots/1
  def show
  end

  # GET /chucky_bots/new
  def new
    @chucky_bot = ChuckyBot.new
    #convierto los role names en keys con values nil en una hash
    @chucky_bot.authorization = Hash[Role.all.pluck(:name).map {|key| [key, nil]}]
    @chucky_bot.public_activity = {actions: nil, notes: nil}
  end

  # GET /chucky_bots/1/edit
  def edit
  end

  # POST /chucky_bots
  def create
    if @chucky_bot.save
      redirect_to dev_chucky_bot_url(@chucky_bot), notice: t("simple_form.flash.successfully_created")
    else
      generate_flash_msg_no_keep(@chucky_bot)
      render :new
    end
  end

  # PATCH/PUT /chucky_bots/1
  def update
    if @chucky_bot.update(chucky_bot_params)
      redirect_to dev_chucky_bot_url(@chucky_bot), notice: t("simple_form.flash.successfully_updated")
    else
      generate_flash_msg_no_keep(@chucky_bot)
      render :edit
    end
  end

  # DELETE /chucky_bots/1
  def destroy
    if @chucky_bot.destroy
      redirect_to dev_chucky_bots_url, notice: t("simple_form.flash.successfully_destroyed")
    else
      generate_flash_msg(@chucky_bot)
      redirect_to :back
    end
  end

  private

    # Only allow a trusted parameter "white list" through.
    def chucky_bot_params
      params.require(:chucky_bot).permit(:underscore_model_name, :i18n_singular_name, :i18n_plural_name, :fa_icon, :migrate,
                                         {authorization: Role.all.pluck(:name).concat([:notes])},
                                         {public_activity: [:actions, :notes]},
                                         {fields_attributes: [:name, :field_type, :i18n_name, :_destroy, :id,
                                                              formats_options: [:index, :show, :all],
                                                              validations_options: [:notes, validates: []],
                                                              association_options: [:no_relationize, :drop_down_type, :dependent_on_parent] ]}
      )
    end
end

app/helpers/chucky_bots_helper.rb
module ChuckyBotsHelper
end

app/views/chucky_bots/_form.html.erb
<div>
      <%= simple_form_for @chucky_bot, html: {class: 'form-horizontal'},
                          wrapper: :horizontal_form,
                          wrapper_mappings: {
                                  check_boxes: :horizontal_radio_and_checkboxes,
                                  radio_buttons: :horizontal_radio_and_checkboxes,
                                  file: :horizontal_file_input,
                                  boolean: :horizontal_boolean
                          } do |f| %>
          <%= f.error_notification %>
          <div class="form-inputs">
            <%= f.input :underscore_model_name, hint: 'underscore_model_name' %>
            <%= f.input :i18n_singular_name %>
            <%= f.input :i18n_plural_name %>
            <%= f.input :fa_icon, hint: 'ej: fa-fw fa fa-user' %>
            <%= f.input :migrate %>

            <%= f.simple_fields_for :public_activity, OpenStruct.new(@chucky_bot.public_activity) do |public_activity_f| %>
                <h2>public_activity</h2>
                <%= public_activity_f.input :actions, hint: 'create:update:destroy' %>
                <%= public_activity_f.input :notes, as: :text, label: 'Notas', hint: 'escriba todo lo que quiera avisar/aclarar al respecto de public activity' %>
            <% end %>

            <h2>authorization</h2>
            <%= f.simple_fields_for :authorization, OpenStruct.new(@chucky_bot.authorization) do |authorization_f| %>
                <% @chucky_bot.authorization.keys.each do |field_name| %>
                    <%= authorization_f.input field_name, hint: 'create-read-update-destroy-whatever o manage' unless ['notes', :notes].include?(field_name) %>
                <% end %>
                <%= authorization_f.input :notes, as: :text, label: 'Notas', hint: 'escriba todo lo que quiera avisar/aclarar al respecto de atorización' %>
            <% end %>


            <h2>fields</h2>
            <%= f.simple_fields_for :fields do |builder| %>
                <%= render 'field_fields', f: builder %>
            <% end %>
            <%= link_to_add_fields "Add Field", f, :fields %>

          </div>

          <div class="form-actions">
            <div class="btn-group">
              <%= link_to raw('<i class="fa fa-arrow-left"></i> Back'), chucky_bots_path, class: 'btn btn-default btn-sm' if can?(:read, ChuckyBot) %>
              <%= link_to raw('<i class="fa fa-binoculars"></i> Show'), @chucky_bot, class: 'btn btn-default btn-sm' if can?(:read, ChuckyBot) && updating? %>
              <%= link_to raw('<i class="fa fa-trash"></i> Destroy'), @chucky_bot, class: 'btn btn-default btn-sm', method: :delete, data: {confirm: 'Are you sure?', 'original-title': 'Destroy'} if can?(:destroy, ChuckyBot) && updating? %>
              <%= f.button :submit, class: 'btn btn-primary btn-sm' %>
            </div>
          </div>
      <% end %>
</div>

app/views/chucky_bots/_index_content.html.erb
<div>
  <%= link_to raw('<i class="fa fa-file"></i> New'), new_chucky_bot_path, class: 'btn btn-sm btn-primary' if (can? :create, ChuckyBot) %>
  <a aria-expanded="false" aria-controls="filters" data-toggle="collapse" href="#filters" role="button" class="btn btn-sm btn-primary"><i class="fa fa-filter"></i>
    Filter</a>
</div>

<div id="filters" class="collapse">
  <%= search_form_for(@q, html: {name: 'filter_form', class: 'form-inline'}) do |f| %>
      <div class="form-group">
        <label for="q[underscore_model_name_cont]">underscore_model_name</label>
        <%= f.search_field :underscore_model_name_cont, label: false, class: "form-control input-sm" %>
      </div>
      <div class="form-group">
        <label for="q[i18n_singular_name_cont]">i18n_singular_name</label>
        <%= f.search_field :i18n_singular_name_cont, label: false, class: "form-control input-sm" %>
      </div>
      <div class="form-group">
        <label for="q[i18n_plural_name_cont]">i18n_plural_name</label>
        <%= f.search_field :i18n_plural_name_cont, label: false, class: "form-control input-sm" %>
      </div>
      <div class="form-group">
        <label for="q[migrate_eq]">migrate</label>
        <%= f.select :migrate_eq, options_for_select([['True', 'true'], ['False', 'false']], @q.migrate_eq), {include_blank: true}, {class: "form-control input-sm"} %>
      </div>
      <div class="form-actions no-padding">
        <div>
          <button type="submit" class="btn btn-sm btn-default form-control" name="search_clear" value="true" id="search_clear">Reset</button>
          <button type="submit" class="btn btn-sm btn-primary form-control">Filter</button>
        </div>
      </div>
  <% end %>
</div>

<table id="dt_basic" width="100%" class="display responsive table table-striped table-bordered table-hover">
  <thead>
  <tr>
    <th><%= sort_link(@q, :underscore_model_name, 'underscore_model_name') %></th>
    <th><%= sort_link(@q, :i18n_singular_name, 'i18n_singular_name') %></th>
    <th><%= sort_link(@q, :i18n_plural_name, 'i18n_plural_name') %></th>
    <th><%= sort_link(@q, :migrate, 'migrate') %></th>
    <th class="all">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @chucky_bots.each do |chucky_bot| %>
      <tr class=<%= cycle('alternate-row', '') %>>
        <td><%= chucky_bot.underscore_model_name %></td>
        <td><%= chucky_bot.i18n_singular_name %></td>
        <td><%= chucky_bot.i18n_plural_name %></td>
        <td align='center;'><%= chucky_bot.migrate %></td>
        <td class="table-actions">
          <%= render 'shared/action_icons', :locals => {:target => chucky_bot, :model_edit_path => edit_chucky_bot_path(chucky_bot)} %>
        </td>
      </tr>
      </tbody>
  <% end %>
  </table>

<%= render 'shared/pagination', locals: {target: @chucky_bots, model_index_path: chucky_bots_path} %>