config/routes.rb
Rails.application.routes.draw do

  resources :nomina_documents
  resources :dashboard
  resources :open_data
  resources :social_users
  resources :api_keys
  resources :verifications
  resources :ley_articulos, shallow: true do
    put 'validar_documento', on: :member
    resources :ley_fraccions do
      put 'validar_documento', on: :member
      collection do
        get 'new_import'
        post 'create_import'
        get 'download_import_file'
      end
    end
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :staffs do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :job_titles do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :ascriptions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :territorial_units do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :social_development_programs
  resources :suppliers
  resources :towns do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :states do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end

  resources :financial_document_types

  resources :projects, shallow: true do
    resources :project_activity_obras, shallow: true do
      resources :financial_documents do
        get 'new_with_type', on: :collection
      end
    end
    resources :project_activity_socials, shallow: true do
      resources :beneficiaries do
        collection do
          get 'new_import'
          post 'create_import'
          get 'download_import_file'
        end
      end
      resources :financial_documents do
        get 'new_with_type', on: :collection
      end
    end
    resources :project_activity_adquisicions, shallow: true do
      resources :financial_documents do
        get 'new_with_type', on: :collection
      end
    end
  end
  resources :key_analyticals do
    put :approve_changes, on: :member
    put :reject_changes, on: :member
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ppr_spending_destinations do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_uni_measure_units do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_are_areas
  resources :cat_ppr_digit_identifiers
  resources :cat_ppr_par_partida_especificas do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ppr_par_partida_genericas do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ppr_par_concepts do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ppr_par_chapters
  resources :cat_ppr_expense_types
  resources :cat_aci_institutional_activities do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ere_subresults do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ere_results do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ere_expending_focus do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_cfu_subfunctions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_cfu_functions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_cfu_finalities
  resources :cat_fon_funds
  resources :cat_fon_origin_resources
  resources :cat_fon_year_documents
  resources :cat_fon_specific_sources
  resources :cat_fon_generic_sources
  resources :cat_fon_funding_sources
  resources :cat_pgd_line_of_actions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_pgd_goals do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_pgd_objectives do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_pgd_area_of_opportunities do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_pgd_axis do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_gen_line_of_actions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_gen_strategies do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_gen_axis do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_der_line_of_actions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_der_strategies do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_der_human_rights do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end

  resources :comments
  resources :conversations, only: [:index, :show, :destroy] do
    post :mark_as_read, on: :member
    get :mark_all_as_read, on: :collection
  end
  resources :delayed_jobs
  resources :thing_categories
  resources :wizard
  resources :public_activity
  resources :thing_contacts
  resources :thing_parts
  resources :things do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end

  namespace :dynamic_select do
    get ':thing_id/thing_contacts', to: 'thing_contacts#index', as: 'thing_contacts' # el as: es para que el helper method sea 'dynamic_select_thing_contacts_path' y no 'dynamic_select_path'
  end

  namespace :dev do
    resources :catalog_cleaners do
      post :run_cleaner, on: :collection
    end
    resources :chucky_bots
    resources :examples do
      collection do
        get 'chartkick'
        get 'cors'
      end

    end
  end

  namespace :admin do
    root to: 'application#index'
    resources :settings
  end

  devise_for :users
  resources :users do
    get 'resend_password_instructions/:id', action: 'resend_password_instructions', on: :collection
    get 'mentionables', on: :collection
  end

  devise_for :api_users, controllers: { registrations: 'api_users/registrations', confirmations: 'api_users/confirmations', passwords: 'api_users/passwords' }
  resources :api_users do
    get 'error_when_confirmation', to: 'api_users/welcome#error_when_confirmation', on: :collection
    get 'check_credentials', to: 'api_users/welcome#check_credentials', on: :collection
  end
  get 'api_user_root', to: 'api_users/welcome#welcome'

  get 'set_viewing_year/:viewing_year', to: 'application#set_viewing_year'
  get "application/access_denied"

  get 'welcome/prueba'

  root to: 'dashboard#index'

  api_version(:module => "V1", :path => {:value => "v1"}, :defaults => {:format => "json"}) do
    resources :things
    resources :project_activity_obras
    resources :verifications
    resources :portal do
      collection do
        get :total_budget
        get :budget_by_chapter
        get :treemap
        get :suppliers
        get :mapa_obras
        get :financial_documents
        get :open_data
      end
    end
  end

  api_version(:module => "V2", :path => {:value => "v2"}, :defaults => {:format => "json"}) do
    resources :things
    resources :project_activity_obras
    resources :verifications
    resources :portal do
      collection do
        get 'total_budget/:year', action: 'total_budget'
        get :budget_by_chapter
        get 'treemap/:year', action: 'treemap'
        get 'suppliers/:year', action: 'suppliers'
        get 'mapa_obras/:year', action: 'mapa_obras'
        get 'financial_documents/:year', action: 'financial_documents'
        get :open_data
      end
    end
  end

end

app/models/cat_gen_axi.rb
class CatGenAxi < ActiveRecord::Base
  has_many :key_analyticals, dependent: :restrict_with_error
  has_many :cat_gen_strategies, dependent: :restrict_with_error
  validates :key, :description, presence: true
  validates :key, uniqueness: true
end

app/controllers/cat_gen_axis_controller.rb
class CatGenAxisController < ApplicationController
  load_and_authorize_resource except: :index, param_method: :cat_gen_axi_params

  # GET /cat_gen_axis
  def index
    @cat_gen_axis = indexize(CatGenAxi)
  end

  # GET /cat_gen_axis/1
  def show
  end

  # GET /cat_gen_axis/new
  def new
  end

  # GET /cat_gen_axis/1/edit
  def edit
  end

  # POST /cat_gen_axis
  def create

    if @cat_gen_axi.save
      redirect_to @cat_gen_axi, notice: t("simple_form.flash.successfully_created")
    else
      generate_flash_msg_no_keep(@cat_gen_axi)
      render :new
    end
  end

  # PATCH/PUT /cat_gen_axis/1
  def update
    if @cat_gen_axi.update(cat_gen_axi_params)
      redirect_to @cat_gen_axi, notice: t("simple_form.flash.successfully_updated")
    else
      generate_flash_msg_no_keep(@cat_gen_axi)
      render :edit
    end
  end

  # DELETE /cat_gen_axis/1
  def destroy
    if @cat_gen_axi.destroy
      redirect_to cat_gen_axis_url, notice: t("simple_form.flash.successfully_destroyed")
    else
      generate_flash_msg(@cat_gen_axi)
      redirect_to :back
    end
  end

  private

    # Only allow a trusted parameter "white list" through.
    def cat_gen_axi_params
      params.require(:cat_gen_axi).permit(:key, :description)
    end
end

app/helpers/cat_gen_axis_helper.rb
module CatGenAxisHelper
end

app/views/cat_gen_axis/_form.html.erb
<div id="wid-id-0" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
  <header>
    <h2><%= creating? ? "<i class='fa fa-file'></i>".html_safe : "<i class='fa fa-pencil'></i>".html_safe %></h2>
    <% if creating? %>
        <div class='widget-toolbar hidden-xs'>
          <a href='<%= new_import_cat_gen_axis_path %>' role='button' class='btn btn-primary'><i class='fa fa-upload'></i>Carga
            masiva</a>
        </div>
    <% end %>
  </header>
  <div>
    <div class="widget-body">
      <%= simple_form_for @cat_gen_axi, html: {class: 'form-horizontal'},
                          wrapper: :horizontal_form,
                          wrapper_mappings: {
                                  check_boxes: :horizontal_radio_and_checkboxes,
                                  radio_buttons: :horizontal_radio_and_checkboxes,
                                  file: :horizontal_file_input,
                                  boolean: :horizontal_boolean
                          } do |f| %>
          <div class="form-inputs edit">
            <%= f.input :key %>
            <%= f.input :description, :input_html => {:rows => 4, :cols => 30} %>
            <%= f.input :objetivo, :input_html => {:rows => 4, :cols => 30} %>

            <div class="widget-footer">
              <div class="form-actions">
                <div class="btn-group">
                  <%= link_to raw("<i class='fa fa-arrow-left'></i> #{t('simple_form.buttons.list')}"), cat_gen_axis_path, class: 'btn btn-default btn-sm' if can?(:read, CatGenAxi) %>
                  <%= link_to raw("<i class='fa fa-binoculars'></i> #{t('simple_form.buttons.show')}"), @cat_gen_axi, class: 'btn btn-default btn-sm' if can?(:read, CatGenAxi) && updating? %>
                  <%= link_to raw("<i class='fa fa-trash'></i> #{t('simple_form.buttons.destroy')}"), @cat_gen_axi, class: 'btn btn-default btn-sm', method: :delete, data: {confirm: t('helpers.messages.are_you_sure'), 'original-title': 'Destroy'} if can?(:destroy, CatGenAxi) && updating? %>
                  <button type="submit" class="btn btn-primary btn-sm">
                    <i class='fa fa-check-circle'></i> <%= creating? ? t('simple_form.buttons.create') : t('simple_form.buttons.update') %>
                  </button>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cat_gen_axis/index.html.erb
<section id="widget-grid">
  <div class="row">
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div id="wid-id-0" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
        <header><span class="widget-icon"><i class="fa fa-table"></i></span>

          <div class="widget-toolbar filter-group">
            <%= link_to raw("<i class='fa fa-file'></i> #{t('simple_form.buttons.new')}"), new_cat_gen_axi_path, class: 'btn btn-primary' if (can? :create, CatGenAxi) %>
            <a href="javascript:void(0)" data-target="#filter-wid-id-0" id="filtrar" role="button" class="filter-button btn  <%= @filter_active ? 'btn-danger' : 'btn-primary' %>"><i class="fa fa-filter"></i> <%= @filter_active ? t('simple_form.buttons.filtering') : t('simple_form.buttons.filters') %>
            </a>
          </div>
        </header>
        <div class="no-padding">
          <div class="jarviswidget-editbox filter-zone" id="filter-wid-id-0" style="display:none;">
            <div class="col-md-9 col-sm-12 no-padding"><%= search_form_for(@q, html: {name: 'filter_form', class: 'form-inline'}) do |f| %>
                  <fieldset>
                    <div class="form-group">
                      <label for="q[key_cont]"><%= t('simple_form.labels.defaults.key') %></label>
                      <%= f.search_field :key_cont, label: false, class: "form-control input-sm" %>
                    </div>
                    <div class="form-group">
                      <label for="q[description_cont]"><%= t('simple_form.labels.defaults.description') %></label>
                      <%= f.search_field :description_cont, label: false, class: "form-control input-sm" %>
                    </div>
                    <%= render 'shared/submit_filters' %>
                  </fieldset>
              <% end %>
            </div>
          </div>
          <div class="widget-body">
            <table id="dt_basic" width="100%" class="display table table-striped table-bordered table-hover" style="margin:0 padding-top:0px">
              <thead>
              <tr>
                <th class='all control'><%= sort_link(@q, :key, t('simple_form.labels.defaults.key')) %></th>
                <th><%= sort_link(@q, :description, t('simple_form.labels.defaults.description')) %></th>
                <th><%= sort_link(@q, :objetivo, 'Objetivo') %></th>
                <th class="all"><%= t('simple_form.screen.actions') %></th>
              </tr>
              </thead>
              <tbody>
              <% @cat_gen_axis.each do |cat_gen_axi| %>
                  <tr>
                    <td><%= cat_gen_axi.key %></td>
                    <td><%= cat_gen_axi.description %></td>
                    <td><%= cat_gen_axi.objetivo %></td>
                    <td class="table-actions">
                      <%= render 'shared/action_icons', locals: {target: cat_gen_axi} %>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
            <div class="widget-footer">
              <%= render 'shared/pagination', locals: {target: @cat_gen_axis, model_index_path: cat_gen_axis_path} %>
            </div>
          </div>
        </div>
      </div>
    </article>
  </div>
</section>

app/views/cat_gen_axis/new_import.html.erb
<%= render 'shared/new_import', locals: {entity: CatGenAxi} %>

app/views/cat_gen_axis/show.html.erb
<section id="widget-grid">
  <article class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    <div id="wid-id-0" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
      <header><span class="widget-icon"><i class="fa fa-binoculars"></i></span>
        <div class="widget-toolbar">
          <%= link_to raw("<i class='fa fa-arrow-left'></i> #{t('simple_form.buttons.list')}"), cat_gen_axis_path, class: 'btn btn-primary' %>
          <%= link_to raw("<i class='fa fa-pencil'></i> #{t('simple_form.buttons.edit')}"), edit_cat_gen_axi_path(@cat_gen_axi), class: 'btn btn-primary' if can?(:update, CatGenAxi) %>
        </div>
      </header>
      <div>
        <!-- widget content -->
        <div class="widget-body">

        <table class="table table-striped table-hover grey-blue-table" width="100%" cellspacing="0" id="dt_basic">
            <thead><tr class="hidden"><th></th><th></th></tr></thead> <!-- el thead es necesario para que datatable no de error --> <tbody>
                                        <tr role="row">
              <th><%= t('simple_form.labels.defaults.key') %></th>
              <td>
                                    <%= @cat_gen_axi.key %>
                              </td>
            </tr>
                                        <tr role="row">
              <th><%= t('simple_form.labels.defaults.description') %></th>
              <td>
                                    <%= @cat_gen_axi.description %>
                              </td>
            </tr>
                        </tbody>
          </table>
        </div>
      </div>
    </div>
  </article>

  <!--
  <article class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    <div id="wid-id-1" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
      <header><span class="widget-icon"><i class="fa fa-info"></i></span>
        <h2>Details</h2>
      </header>
      <div class="no-padding">
        <div class="widget-body">

        </div>
      </div>
    </div>
  </article>
  -->
</section>