config/routes.rb
Rails.application.routes.draw do

  resources :nomina_documents
  resources :dashboard
  resources :open_data
  resources :social_users
  resources :api_keys
  resources :verifications
  resources :ley_articulos, shallow: true do
    put 'validar_documento', on: :member
    resources :ley_fraccions do
      put 'validar_documento', on: :member
      collection do
        get 'new_import'
        post 'create_import'
        get 'download_import_file'
      end
    end
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :staffs do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :job_titles do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :ascriptions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :territorial_units do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :social_development_programs
  resources :suppliers
  resources :towns do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :states do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end

  resources :financial_document_types

  resources :projects, shallow: true do
    resources :project_activity_obras, shallow: true do
      resources :financial_documents do
        get 'new_with_type', on: :collection
      end
    end
    resources :project_activity_socials, shallow: true do
      resources :beneficiaries do
        collection do
          get 'new_import'
          post 'create_import'
          get 'download_import_file'
        end
      end
      resources :financial_documents do
        get 'new_with_type', on: :collection
      end
    end
    resources :project_activity_adquisicions, shallow: true do
      resources :financial_documents do
        get 'new_with_type', on: :collection
      end
    end
  end
  resources :key_analyticals do
    put :approve_changes, on: :member
    put :reject_changes, on: :member
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ppr_spending_destinations do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_uni_measure_units do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_are_areas
  resources :cat_ppr_digit_identifiers
  resources :cat_ppr_par_partida_especificas do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ppr_par_partida_genericas do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ppr_par_concepts do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ppr_par_chapters
  resources :cat_ppr_expense_types
  resources :cat_aci_institutional_activities do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ere_subresults do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ere_results do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ere_expending_focus do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_cfu_subfunctions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_cfu_functions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_cfu_finalities
  resources :cat_fon_funds
  resources :cat_fon_origin_resources
  resources :cat_fon_year_documents
  resources :cat_fon_specific_sources
  resources :cat_fon_generic_sources
  resources :cat_fon_funding_sources
  resources :cat_pgd_line_of_actions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_pgd_goals do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_pgd_objectives do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_pgd_area_of_opportunities do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_pgd_axis do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_gen_line_of_actions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_gen_strategies do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_gen_axis do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_der_line_of_actions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_der_strategies do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_der_human_rights do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end

  resources :comments
  resources :conversations, only: [:index, :show, :destroy] do
    post :mark_as_read, on: :member
    get :mark_all_as_read, on: :collection
  end
  resources :delayed_jobs
  resources :thing_categories
  resources :wizard
  resources :public_activity
  resources :thing_contacts
  resources :thing_parts
  resources :things do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end

  namespace :dynamic_select do
    get ':thing_id/thing_contacts', to: 'thing_contacts#index', as: 'thing_contacts' # el as: es para que el helper method sea 'dynamic_select_thing_contacts_path' y no 'dynamic_select_path'
  end

  namespace :dev do
    resources :catalog_cleaners do
      post :run_cleaner, on: :collection
    end
    resources :chucky_bots
    resources :examples do
      collection do
        get 'chartkick'
        get 'cors'
      end

    end
  end

  namespace :admin do
    root to: 'application#index'
    resources :settings
  end

  devise_for :users
  resources :users do
    get 'resend_password_instructions/:id', action: 'resend_password_instructions', on: :collection
    get 'mentionables', on: :collection
  end

  devise_for :api_users, controllers: { registrations: 'api_users/registrations', confirmations: 'api_users/confirmations', passwords: 'api_users/passwords' }
  resources :api_users do
    get 'error_when_confirmation', to: 'api_users/welcome#error_when_confirmation', on: :collection
    get 'check_credentials', to: 'api_users/welcome#check_credentials', on: :collection
  end
  get 'api_user_root', to: 'api_users/welcome#welcome'

  get 'set_viewing_year/:viewing_year', to: 'application#set_viewing_year'
  get "application/access_denied"

  get 'welcome/prueba'

  root to: 'dashboard#index'

  api_version(:module => "V1", :path => {:value => "v1"}, :defaults => {:format => "json"}) do
    resources :things
    resources :project_activity_obras
    resources :verifications
    resources :portal do
      collection do
        get :total_budget
        get :budget_by_chapter
        get :treemap
        get :suppliers
        get :mapa_obras
        get :financial_documents
        get :open_data
      end
    end
  end

  api_version(:module => "V2", :path => {:value => "v2"}, :defaults => {:format => "json"}) do
    resources :things
    resources :project_activity_obras
    resources :verifications
    resources :portal do
      collection do
        get 'total_budget/:year', action: 'total_budget'
        get :budget_by_chapter
        get 'treemap/:year', action: 'treemap'
        get 'suppliers/:year', action: 'suppliers'
        get 'mapa_obras/:year', action: 'mapa_obras'
        get 'financial_documents/:year', action: 'financial_documents'
        get :open_data
      end
    end
  end

end

app/models/ascription.rb
class Ascription < ActiveRecord::Base
  has_many :staffs, dependent: :restrict_with_error
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/ascriptions_controller.rb
class AscriptionsController < ApplicationController
  load_and_authorize_resource except: :index, param_method: :ascription_params

  # GET /ascriptions
  def index
    @ascriptions = indexize(Ascription)
  end

  # GET /ascriptions/1
  def show
  end

  # GET /ascriptions/new
  def new
  end

  # GET /ascriptions/1/edit
  def edit
  end

  # POST /ascriptions
  def create

    if @ascription.save
      redirect_to @ascription, notice: t("simple_form.flash.successfully_created")
    else
      generate_flash_msg_no_keep(@ascription)
      render :new
    end
  end

  # PATCH/PUT /ascriptions/1
  def update
    if @ascription.update(ascription_params)
      redirect_to @ascription, notice: t("simple_form.flash.successfully_updated")
    else
      generate_flash_msg_no_keep(@ascription)
      render :edit
    end
  end

  # DELETE /ascriptions/1
  def destroy
    if @ascription.destroy
      redirect_to ascriptions_url, notice: t("simple_form.flash.successfully_destroyed")
    else
      generate_flash_msg(@ascription)
      redirect_to ascriptions_url
    end
  end

  private

    # Only allow a trusted parameter "white list" through.
    def ascription_params
      params.require(:ascription).permit(:name)
    end
end

app/helpers/ascriptions_helper.rb
module AscriptionsHelper
end

app/views/ascriptions/_form.html.erb
<div id="wid-id-0" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
  <header>
    <h2><%= creating? ? "<i class='fa fa-file'></i>".html_safe : "<i class='fa fa-pencil'></i>".html_safe %></h2>

    <% if creating? %>
        <div class='widget-toolbar hidden-xs'>
          <a href='<%= new_import_ascriptions_path %>' role='button' class='btn btn-primary'><i class='fa fa-upload'></i>Carga masiva</a>
        </div>
    <% end %>

  </header>
  <div>
    <div class="widget-body">
      <%= simple_form_for @ascription, html: { class: 'form-horizontal' },
                          wrapper: :horizontal_form,
                          wrapper_mappings: {
                                  check_boxes: :horizontal_radio_and_checkboxes,
                                  radio_buttons: :horizontal_radio_and_checkboxes,
                                  file: :horizontal_file_input,
                                  boolean: :horizontal_boolean
                          } do |f| %>
          <div class="form-inputs edit">
                                    <%= f.input :name %>
                
            <div class="widget-footer">
              <div class="form-actions">
                <div class="btn-group">
                  <%= link_to raw("<i class='fa fa-arrow-left'></i> #{t('simple_form.buttons.list')}"), ascriptions_path, class: 'btn btn-default btn-sm' if can?(:read, Ascription) %>
                  <%= link_to raw("<i class='fa fa-binoculars'></i> #{t('simple_form.buttons.show')}"), @ascription, class: 'btn btn-default btn-sm' if can?(:read, Ascription) && updating? %>
                  <%= link_to raw("<i class='fa fa-trash'></i> #{t('simple_form.buttons.destroy')}"), @ascription, class: 'btn btn-default btn-sm', method: :delete, data: {confirm: t('helpers.messages.are_you_sure'), 'original-title': 'Destroy'} if can?(:destroy, Ascription) && updating? %>
                  <button type="submit" class="btn btn-primary btn-sm"><i class='fa fa-check-circle'></i> <%= creating? ? t('simple_form.buttons.create') : t('simple_form.buttons.update') %></button>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/ascriptions/edit.html.erb
<%= render 'form' %>

app/views/ascriptions/index.html.erb
<section id="widget-grid">
  <div class="row">
    <article class="col-xs-12">
      <div id="wid-id-0" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
        <header><span class="widget-icon"><i class="fa fa-table"></i></span>

          <div class="widget-toolbar filter-group">
            <%= link_to raw("<i class='fa fa-file'></i> #{t('simple_form.buttons.new')}"), new_ascription_path, class: 'btn btn-primary' if (can? :create, Ascription) %>
            <a href="javascript:void(0)" data-target="#filter-wid-id-0" id="filtrar" role="button" class="filter-button btn <%= @filter_active ? 'btn-danger' : 'btn-primary' %>"><i class="fa fa-filter"></i> <%= @filter_active ? t('simple_form.buttons.filtering') : t('simple_form.buttons.filters') %>
            </a>
          </div>
        </header>
        <div class="no-padding">
          <div class="jarviswidget-editbox filter-zone" id="filter-wid-id-0" style="display:none;">
            <div class="col-xs-12"><%= search_form_for(@q, html: {name: 'filter_form', class: 'form-inline'}) do |f| %>
                  <fieldset>
                    <div class="row">
                      <div class="col-md-3 col-sm-6 col-xs-12">
                        <label for="q[name_cont]"><%= t('simple_form.labels.defaults.name') %></label>
                        <%= f.search_field :name_cont, label: false, class: "form-control input-sm" %>
                      </div>
                    </div>
                    <div class="row pull-right">
                      <div class="col-sm-12">
                        <%= render 'shared/submit_filters' %>
                      </div>
                    </div>
                  </fieldset>
              <% end %>
            </div>
          </div>
          <div class="widget-body">
            <table id="dt_basic" width="100%" class="display table table-striped table-bordered table-hover" style="margin:0 padding-top:0px">
              <thead>
              <tr>
                <th class='all control'><%= sort_link(@q, :name, t('simple_form.labels.defaults.name')) %></th>
                <th class="all"><%= t('simple_form.screen.actions') %></th>
              </tr>
              </thead>
              <tbody>
              <% @ascriptions.each do |ascription| %>
                  <tr>
                    <td><%= ascription.name %></td>
                    <td class="table-actions">
                      <%= render 'shared/action_icons', locals: {target: ascription} %>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
            <div class="widget-footer">
              <%= render 'shared/pagination', locals: {target: @ascriptions, model_index_path: ascriptions_path} %>
            </div>
          </div>
        </div>
      </div>
    </article>
  </div>
</section>

app/views/ascriptions/new.html.erb
<%= render 'form' %>

app/views/ascriptions/new_import.html.erb
<%= render 'shared/new_import', locals: {entity: Ascription} %>

app/views/ascriptions/show.html.erb
<section id="widget-grid">
  <article class="col-sm-6">
    <div id="wid-id-0" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
      <header><span class="widget-icon"><i class="fa fa-binoculars"></i></span>
        <div class="widget-toolbar">
          <%= link_to raw("<i class='fa fa-arrow-left'></i> #{t('simple_form.buttons.list')}"), ascriptions_path, class: 'btn btn-primary' %>
          <%= link_to raw("<i class='fa fa-pencil'></i> #{t('simple_form.buttons.edit')}"), edit_ascription_path(@ascription), class: 'btn btn-primary' if can?(:update, Ascription) %>
        </div>
      </header>
      <div class="no-padding">
        <!-- widget content -->
        <div class="widget-body">

          <div class="form-group">

            <div class="row show-details">
              <label class="col-lg-3 col-md-4 control-label">
                <strong><%= t('simple_form.labels.defaults.name') %></strong>
              </label>
              <div class="col-lg-9 details-data"><%= @ascription.name %></div>
            </div>

          </div>

        </div>
      </div>
    </div>
  </article>

  <!--
  <article class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    <div id="wid-id-1" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
      <header><span class="widget-icon"><i class="fa fa-info"></i></span>
        <h2>Details</h2>
      </header>
      <div class="no-padding">
        <div class="widget-body">

        </div>
      </div>
    </div>
  </article>
-->
</section>

<script type="text/javascript">
  $('.show-details:even').addClass('striped-div');
</script>