config/routes.rb
Rails.application.routes.draw do

  resources :nomina_documents
  resources :dashboard
  resources :open_data
  resources :social_users
  resources :api_keys
  resources :verifications
  resources :ley_articulos, shallow: true do
    put 'validar_documento', on: :member
    resources :ley_fraccions do
      put 'validar_documento', on: :member
      collection do
        get 'new_import'
        post 'create_import'
        get 'download_import_file'
      end
    end
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :staffs do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :job_titles do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :ascriptions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :territorial_units do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :social_development_programs
  resources :suppliers
  resources :towns do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :states do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end

  resources :financial_document_types

  resources :projects, shallow: true do
    resources :project_activity_obras, shallow: true do
      resources :financial_documents do
        get 'new_with_type', on: :collection
      end
    end
    resources :project_activity_socials, shallow: true do
      resources :beneficiaries do
        collection do
          get 'new_import'
          post 'create_import'
          get 'download_import_file'
        end
      end
      resources :financial_documents do
        get 'new_with_type', on: :collection
      end
    end
    resources :project_activity_adquisicions, shallow: true do
      resources :financial_documents do
        get 'new_with_type', on: :collection
      end
    end
  end
  resources :key_analyticals do
    put :approve_changes, on: :member
    put :reject_changes, on: :member
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ppr_spending_destinations do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_uni_measure_units do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_are_areas
  resources :cat_ppr_digit_identifiers
  resources :cat_ppr_par_partida_especificas do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ppr_par_partida_genericas do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ppr_par_concepts do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ppr_par_chapters
  resources :cat_ppr_expense_types
  resources :cat_aci_institutional_activities do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ere_subresults do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ere_results do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_ere_expending_focus do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_cfu_subfunctions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_cfu_functions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_cfu_finalities
  resources :cat_fon_funds
  resources :cat_fon_origin_resources
  resources :cat_fon_year_documents
  resources :cat_fon_specific_sources
  resources :cat_fon_generic_sources
  resources :cat_fon_funding_sources
  resources :cat_pgd_line_of_actions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_pgd_goals do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_pgd_objectives do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_pgd_area_of_opportunities do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_pgd_axis do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_gen_line_of_actions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_gen_strategies do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_gen_axis do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_der_line_of_actions do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_der_strategies do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end
  resources :cat_der_human_rights do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end

  resources :comments
  resources :conversations, only: [:index, :show, :destroy] do
    post :mark_as_read, on: :member
    get :mark_all_as_read, on: :collection
  end
  resources :delayed_jobs
  resources :thing_categories
  resources :wizard
  resources :public_activity
  resources :thing_contacts
  resources :thing_parts
  resources :things do
    collection do
      get 'new_import'
      post 'create_import'
      get 'download_import_file'
    end
  end

  namespace :dynamic_select do
    get ':thing_id/thing_contacts', to: 'thing_contacts#index', as: 'thing_contacts' # el as: es para que el helper method sea 'dynamic_select_thing_contacts_path' y no 'dynamic_select_path'
  end

  namespace :dev do
    resources :catalog_cleaners do
      post :run_cleaner, on: :collection
    end
    resources :chucky_bots
    resources :examples do
      collection do
        get 'chartkick'
        get 'cors'
      end

    end
  end

  namespace :admin do
    root to: 'application#index'
    resources :settings
  end

  devise_for :users
  resources :users do
    get 'resend_password_instructions/:id', action: 'resend_password_instructions', on: :collection
    get 'mentionables', on: :collection
  end

  devise_for :api_users, controllers: { registrations: 'api_users/registrations', confirmations: 'api_users/confirmations', passwords: 'api_users/passwords' }
  resources :api_users do
    get 'error_when_confirmation', to: 'api_users/welcome#error_when_confirmation', on: :collection
    get 'check_credentials', to: 'api_users/welcome#check_credentials', on: :collection
  end
  get 'api_user_root', to: 'api_users/welcome#welcome'

  get 'set_viewing_year/:viewing_year', to: 'application#set_viewing_year'
  get "application/access_denied"

  get 'welcome/prueba'

  root to: 'dashboard#index'

  api_version(:module => "V1", :path => {:value => "v1"}, :defaults => {:format => "json"}) do
    resources :things
    resources :project_activity_obras
    resources :verifications
    resources :portal do
      collection do
        get :total_budget
        get :budget_by_chapter
        get :treemap
        get :suppliers
        get :mapa_obras
        get :financial_documents
        get :open_data
      end
    end
  end

  api_version(:module => "V2", :path => {:value => "v2"}, :defaults => {:format => "json"}) do
    resources :things
    resources :project_activity_obras
    resources :verifications
    resources :portal do
      collection do
        get 'total_budget/:year', action: 'total_budget'
        get :budget_by_chapter
        get 'treemap/:year', action: 'treemap'
        get 'suppliers/:year', action: 'suppliers'
        get 'mapa_obras/:year', action: 'mapa_obras'
        get 'financial_documents/:year', action: 'financial_documents'
        get :open_data
      end
    end
  end

end

app/models/verification.rb
class Verification < ActiveRecord::Base
  belongs_to :project_activity_obra
  belongs_to :verification_owneable, polymorphic: true
  has_many :verification_photos, dependent: :destroy

  accepts_nested_attributes_for :verification_photos, allow_destroy: true

  attr_accessor :photos # esto es para que la app movil envia este parametro con un string que sea el json de toddas las fotos. para que sea mas facil de programar en la app

  validates :verification_owneable_id, :verification_owneable_type, :project_activity_obra_id, :answer, :evaluation, :status, presence: true
  validates :verification_owneable_id, :project_activity_obra_id, :answer, :evaluation, :status, numericality: true

  validates :answer, inclusion: 0..1
  validates :evaluation, inclusion: 1..5
  validates :status, inclusion: -1..1

  scope :by_user, -> (user){where(verification_owneable: user)}
  scope :validas, -> {where(status: 1)}
  scope :validas_or_sin_revisar, -> {where('status = 1 OR status = -1')}
  scope :for_today, -> {where('created_at BETWEEN ? AND ?', DateTime.now.beginning_of_day, DateTime.now.end_of_day)}
end

app/controllers/v1/verifications_controller.rb
class V1::VerificationsController < V1::BaseController
  respond_to :json

  # estas son las verificaciones realizadas por el usuario
  def index
    @verifications = Verification.by_user(current_user).includes(:project_activity_obra)
  end

  def create
    # {verification_photos_attributes: [:id, :url, :date_and_time, :latitude, :longitude]}
    verification = Verification.new(verification_params)
    verification.verification_owneable = current_user
    ActiveSupport::JSON.decode(verification.photos).each do |photo|
      verification.verification_photos << VerificationPhoto.new(photo)
    end
    verification.save
    respond_with verification
  end

  private

    # Only allow a trusted parameter "white list" through.
    def verification_params
      params.require(:verification).permit(:photos, :project_activity_obra_id, :answer, :evaluation, :comments, :status)
    end
end

app/controllers/v2/verifications_controller.rb
class V2::VerificationsController < V2::BaseController
  respond_to :json

  # estas son las verificaciones realizadas por el usuario
  def index
    @verifications = Verification.by_user(current_user).includes(:project_activity_obra)
  end

  def create
    # {verification_photos_attributes: [:id, :url, :date_and_time, :latitude, :longitude]}
    verification = Verification.new(verification_params)
    verification.verification_owneable = current_user
    ActiveSupport::JSON.decode(verification.photos).each do |photo|
      verification.verification_photos << VerificationPhoto.new(photo)
    end
    verification.save
    respond_with verification
  end

  private

    # Only allow a trusted parameter "white list" through.
    def verification_params
      params.require(:verification).permit(:photos, :project_activity_obra_id, :answer, :evaluation, :comments, :status)
    end
end

app/controllers/verifications_controller.rb
class VerificationsController < ApplicationController
  load_and_authorize_resource except: :index, param_method: :verification_params

  # GET /verifications
  def index
    @verifications = indexize(Verification)
  end

  # GET /verifications/1
  def show
  end

  # GET /verifications/new
  def new
  end

  # GET /verifications/1/edit
  def edit
  end

  # POST /verifications
  def create
    @verification.verification_owneable = current_user
    if @verification.save
      redirect_to @verification, notice: t("simple_form.flash.successfully_created")
    else
      generate_flash_msg_no_keep(@verification)
      puts @verification.errors.full_messages.to_s
      render :new
    end
  end

  # PATCH/PUT /verifications/1
  def update
    @verification.verification_owneable = current_user unless @verification.verification_owneable
    if @verification.update(verification_params)
      redirect_to @verification, notice: t("simple_form.flash.successfully_updated")
    else
      generate_flash_msg_no_keep(@verification)
      render :edit
    end
  end

  # DELETE /verifications/1
  def destroy
    if @verification.destroy
      redirect_to verifications_url, notice: t("simple_form.flash.successfully_destroyed")
    else
      generate_flash_msg(@verification)
      redirect_to verifications_url
    end
  end

  private

    # Only allow a trusted parameter "white list" through.
    def verification_params
      params.require(:verification).permit({verification_photos_attributes: [:id, :name, :date_and_time, :latitude, :longitude, :_destroy]}, :project_activity_obra_id, :answer, :evaluation, :comments, :status)
    end
end

app/helpers/verifications_helper.rb
module VerificationsHelper
  def status_icon(status)
    case status
      when -1
        'Sin Revisar'
      when 1
        "<p style='font-size:20px;'><i class='fa-fw fa fa-check-circle' style='color:green;'></i></p>".html_safe
      when 0
        "<p style='font-size:20px;'><i class='fa-fw fa fa-times-circle' style='color:red;'></i></p>".html_safe
      else
        raise 'Verificación con status erroneo'
    end
  end

  def humanize_answer(answer)
    case answer
      when 1
        'Sí'
      when 0
        'No'
      else
        raise 'Valor de respuesta erroneo'
    end
  end

end

app/views/verifications/_form.html.erb
<div id="wid-id-0" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
  <header>
    <h2><%= creating? ? "<i class='fa fa-file'></i>".html_safe : "<i class='fa fa-pencil'></i>".html_safe %></h2>
  </header>
  <div>
    <div class="widget-body">
      <%= simple_nested_form_for @verification, html: {class: 'form-horizontal'},
                          wrapper: :horizontal_form,
                          wrapper_mappings: {
                                  check_boxes: :horizontal_radio_and_checkboxes,
                                  radio_buttons: :horizontal_radio_and_checkboxes,
                                  file: :horizontal_file_input,
                                  boolean: :horizontal_boolean
                          } do |f| %>
          <div class="form-inputs edit">
            <%#= f.association :user %>
            <%= f.association :project_activity_obra %>
            <%= f.input :answer, as: :select, collection: [['Sí', 1], ['No', 0]], include_blank: false %>
            <%= f.input :evaluation %>
            <%= f.input :comments, :input_html => {:rows => 4, :cols => 30} %>

            <div class="form-group">
              <label class="col-xs-12 col-sm-3 control-label" for="">Fotos</label>
              <div class="col-sm-9">
                <div class="table-responsive">
                  <table id="verification_photos" width="100%" class="display tableAlt table-striped table-bordered table-hover no-margin" style="margin:0 padding-top:0px">
                    <tr>
                      <th class="all control">Nombre</th>
                      <th>Latitud</th>
                      <th>Longitud</th>
                      <th>Fecha y hora</th>
                      <th class="all"></th>
                    </tr>
                    <%= f.fields_for :verification_photos, :wrapper => false do |verification_photo_form| %>
                        <tr class="fields">
                          <td><%= verification_photo_form.input :name, wrapper: :clean %></td>
                          <td><%= verification_photo_form.input :latitude, wrapper: :clean %></td>
                          <td><%= verification_photo_form.input :longitude, wrapper: :clean %></td>
                          <td><%= format_datetime_field(verification_photo_form.object.try(:date_and_time)) %></td>
                          <td align="center">
                            <%= verification_photo_form.link_to_remove do %>
                                <i class="fa fa-trash-o" data-original-title="Eliminar" data-placement="top" rel="tooltip"></i>
                            <% end %>
                          </td>
                        </tr>
                    <% end %>
                  </table>
                  <div class="well well-sm">
                  <span class="btn bg-color-blue txt-color-white btn-xs">
                    <%= f.link_to_add raw("add <i class='fa fa-plus-square'></i>"), :verification_photos, :data => {:target => "#verification_photos"} %>
                  </span>
                  </div>
                </div>
              </div>
            </div>

            <div class="widget-footer">
              <div class="form-actions">
                <div class="btn-group">
                  <%= link_to raw("<i class='fa fa-arrow-left'></i> #{t('simple_form.buttons.list')}"), verifications_path, class: 'btn btn-default btn-sm' if can?(:read, Verification) %>
                  <%= link_to raw("<i class='fa fa-binoculars'></i> #{t('simple_form.buttons.show')}"), @verification, class: 'btn btn-default btn-sm' if can?(:read, Verification) && updating? %>
                  <%= link_to raw("<i class='fa fa-trash'></i> #{t('simple_form.buttons.destroy')}"), @verification, class: 'btn btn-default btn-sm', method: :delete, data: {confirm: t('helpers.messages.are_you_sure'), 'original-title': 'Destroy'} if can?(:destroy, Verification) && updating? %>
                  <button type="submit" class="btn btn-primary btn-sm">
                    <i class='fa fa-check-circle'></i> <%= creating? ? t('simple_form.buttons.create') : t('simple_form.buttons.update') %>
                  </button>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/verifications/edit.html.erb
<%= render 'form' %>

app/views/verifications/index.html.erb
<section id="widget-grid">
  <div class="row">
    <article class="col-xs-12">
      <div id="wid-id-0" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
        <header><span class="widget-icon"><i class="fa fa-table"></i></span>

          <div class="widget-toolbar filter-group">
            <%= link_to raw("<i class='fa fa-file'></i> #{t('simple_form.buttons.new')}"), new_verification_path, class: 'btn btn-primary' if (can? :create, Verification) %>
            <a href="javascript:void(0)" data-target="#filter-wid-id-0" id="filtrar" role="button" class="filter-button btn <%= @filter_active ? 'btn-danger' : 'btn-primary' %>"><i class="fa fa-filter"></i> <%= @filter_active ? t('simple_form.buttons.filtering') : t('simple_form.buttons.filters') %>
            </a>
          </div>
        </header>
        <div class="no-padding">
          <div class="jarviswidget-editbox filter-zone" id="filter-wid-id-0" style="display:none;">
            <div class="col-xs-12"><%= search_form_for(@q, html: {name: 'filter_form', class: 'form-inline'}) do |f| %>
                  <fieldset>
                    <div class="row">
                      <div class="col-md-3 col-sm-6 col-xs-12">
                        <label for="q[project_activity_obra_id_cont]"><%= t('simple_form.labels.defaults.project_activity_obra') %></label>
                        <%= f.select :project_activity_obra_id_eq, options_from_collection_for_select(ProjectActivityObra.all, :id, :name, @q.project_activity_obra_id_eq), {include_blank: true}, {class: "form-control input-sm"} %>
                      </div>
                      <div class="col-md-3 col-sm-6 col-xs-12">
                        <label for="q[answer_eq]"><%= t('simple_form.labels.defaults.answer') %></label>
                        <%= f.select :answer_eq, options_for_select([['Sí', 1], ['No', 0]], @q.answer_eq), {include_blank: true}, {class: "form-control input-sm"} %>
                      </div>
                      <div class="col-md-3 col-sm-6 col-xs-12 spanning">
                        <label for="q[evaluation_gteq]"><%= t('simple_form.labels.defaults.evaluation') %></label>

                        <div class="input-group input-group-sm block">
                          <%= f.search_field :evaluation_gteq, label: false, placeholder: t('simple_form.placeholders.from'), class: "form-control input-sm" %>
                        </div>
                        <div class="input-group input-group-sm block">
                          <%= f.search_field :evaluation_lteq, label: false, placeholder: t('simple_form.placeholders.to'), class: "form-control input-sm" %>
                        </div>
                      </div>
                      <div class="col-md-3 col-sm-6 col-xs-12">
                        <label for="q[comments_cont]"><%= t('simple_form.labels.defaults.comments') %></label>
                        <%= f.search_field :comments_cont, label: false, class: "form-control input-sm" %>
                      </div>
                      <div class="col-md-3 col-sm-6 col-xs-12">
                        <label for="q[status_eq]"><%= t('simple_form.labels.defaults.status') %></label>
                        <%= f.select :status_eq, options_for_select([['Sin Revisar', -1], ['Válida', 1], ['Inválida', 0]], @q.status_eq), {include_blank: true}, {class: "form-control input-sm"} %>
                      </div>
                    </div>
                    <div class="row pull-right">
                      <div class="col-sm-12">
                        <%= render 'shared/submit_filters' %>
                      </div>
                    </div>
                  </fieldset>
              <% end %>
            </div>
          </div>
          <div class="widget-body">
            <table id="dt_basic" width="100%" class="display table table-striped table-bordered table-hover" style="margin:0 padding-top:0px">
              <thead>
              <tr>
                <th class='all control'><%= t('simple_form.labels.defaults.user') %></th>
                <th><%= sort_link(@q, :project_activity_obra_name, t('simple_form.labels.defaults.project_activity_obra')) %></th>
                <th><%= sort_link(@q, :answer, t('simple_form.labels.defaults.answer')) %></th>
                <th><%= sort_link(@q, :evaluation, t('simple_form.labels.defaults.evaluation')) %></th>
                <th><%= sort_link(@q, :comments, t('simple_form.labels.defaults.comments')) %></th>
                <th><%= sort_link(@q, :status, t('simple_form.labels.defaults.status')) %></th>
                <th class="all"><%= t('simple_form.screen.actions') %></th>
              </tr>
              </thead>
              <tbody>
              <% @verifications.each do |verification| %>
                  <tr>
                    <td><%= verification.verification_owneable.try(:name_or_email) %></td>
                    <td><%= verification.project_activity_obra.try(:name) %></td>
                    <td><%= humanize_answer(verification.answer) %></td>
                    <td align='right'><%= verification.evaluation %></td>
                    <td><%= verification.comments %></td>
                    <td align='center'><%= status_icon(verification.status) %></td>
                    <td class="table-actions">
                      <%= render 'shared/action_icons', locals: {target: verification} %>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
            <div class="widget-footer">
              <%= render 'shared/pagination', locals: {target: @verifications, model_index_path: verifications_path} %>
            </div>
          </div>
        </div>
      </div>
    </article>
  </div>
</section>

app/views/verifications/new.html.erb
<%= render 'form' %>

app/views/verifications/show.html.erb
<section id="widget-grid">
  <article class="col-sm-6">
    <div id="wid-id-0" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
      <header><span class="widget-icon"><i class="fa fa-binoculars"></i></span>

        <div class="widget-toolbar">
          <%= link_to raw("<i class='fa fa-arrow-left'></i> #{t('simple_form.buttons.list')}"), verifications_path, class: 'btn btn-primary' %>
          <%= link_to raw("<i class='fa fa-pencil'></i> #{t('simple_form.buttons.edit')}"), edit_verification_path(@verification), class: 'btn btn-primary' if can?(:update, Verification) %>
          <%= link_to raw("<i class='fa fa-check-circle'></i> Válida"), verification_path(@verification, 'verification[status]' => 1), class: 'btn btn-success btn-sm', method: :put, data: {'original-title': 'Validar Documento'} if(can?(:update, Verification) && @verification.status != 1) %>
          <%= link_to raw("<i class='fa fa-times-circle'></i> Inválida"), verification_path(@verification, 'verification[status]' => 0), class: 'btn btn-danger btn-sm', method: :put, data: {confirm: '¿Está seguro de invalidar esta verificación?', 'original-title': 'Invalidar verificación'} if(can?(:update, Verification) && @verification.status != 0) %>
        </div>
      </header>
      <div class="no-padding">
        <!-- widget content -->
        <div class="widget-body">

          <div class="form-group">

            <div class="row show-details">
              <label class="col-lg-3 col-md-4 control-label">
                <strong><%= t('simple_form.labels.defaults.user') %></strong>
              </label>
              <div class="col-lg-9 details-data"><%= @verification.verification_owneable.try(:name_or_email) %></div>
            </div>

            <div class="row show-details">
              <label class="col-lg-3 col-md-4 control-label">
                <strong><%= t('simple_form.labels.defaults.project_activity_obra') %></strong>
              </label>
              <div class="col-lg-9 details-data"><%= @verification.project_activity_obra.try(:name) %></div>
            </div>

            <div class="row show-details">
              <label class="col-lg-3 col-md-4 control-label">
                <strong><%= t('simple_form.labels.defaults.answer') %></strong>
              </label>
              <div class="col-lg-9 details-data"><%= humanize_answer(@verification.answer) %></div>
            </div>

            <div class="row show-details">
              <label class="col-lg-3 col-md-4 control-label">
                <strong><%= t('simple_form.labels.defaults.evaluation') %></strong>
              </label>
              <div class="col-lg-9 details-data"><%= @verification.evaluation %></div>
            </div>

            <div class="row show-details">
              <label class="col-lg-3 col-md-4 control-label">
                <strong><%= t('simple_form.labels.defaults.comments') %></strong>
              </label>
              <div class="col-lg-9 details-data"><%= @verification.comments %></div>
            </div>

            <div class="row show-details">
              <label class="col-lg-3 col-md-4 control-label">
                <strong><%= t('simple_form.labels.defaults.status') %></strong>
              </label>
              <div class="col-lg-9 details-data"><%= status_icon(@verification.status) %></div>
            </div>

          </div>

        </div>
      </div>
    </div>
  </article>

  <!--
  <article class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
    <div id="wid-id-1" data-widget-colorbutton="false" data-widget-deletebutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" class="jarviswidget jarviswidget-color-darken">
      <header><span class="widget-icon"><i class="fa fa-info"></i></span>
        <h2>Details</h2>
      </header>
      <div class="no-padding">
        <div class="widget-body">

        </div>
      </div>
    </div>
  </article>
  -->

  <!-- Gallery row -->
  <div class="row">
    <!-- SuperBox -->
    <div class="superbox col-sm-12">
        <% @verification.verification_photos.each do |photo| %>
          <% photo_url = "#{Sett['S3_ROOT_PATH']}#{photo.name}" %>
          <div class="superbox-list">
            <div style="background-image: url('<%= photo_url %>');" data-img="<%= photo_url %>" data-alt="Latitud: <%= photo.latitude %>. Longitud: <%= photo.longitude %>" data-title="<%= l(photo.date_and_time, :format => :long) if photo.date_and_time %>" class="superbox-img"></div>
          </div>
        <% end %>
    </div>
    <!-- /SuperBox -->
    <div class="superbox-show" style="height:300px; display: none"></div>
  </div>
  <!-- end Gallery row -->
</section>

<script type="text/javascript">
    // DO NOT REMOVE : GLOBAL FUNCTIONS!
    $(document).ready(function () {
        $('.superbox').SuperBox();
    });
    $('.show-details:even').addClass('striped-div');

</script>